version: "3.8"

services:

  wordpress:
    build:
      context: ./wordpress
    container_name: "wordpress-webserver"
    #volumes:
    #  - "./site:/var/www/localhost/htdocs"
    #  - "./site:/usr/local/apache2/htdocs"
    ports:
      - "80:80"
    
  
  db:
    image: mariadb:latest
    container_name: "mariadb-server"
    restart: always
    environment:
        MARIADB_DATABASE: wordpress
        MARIADB_USER: henry
        MARIADB_PASSWORD: any
        MARIADB_ALLOW_EMPTY_PASSWORD: 1
        MARIADB_ROOT_PASSWORD: cool
    #volumes:
    #  - "./db:/var/lib/mysql"
    

  phpmyadmin:
    
    image: phpmyadmin:latest
    container_name: phpmyadmin-server
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    