from ubuntu:20.04
run apt-get -y update
run apt-get install -y iputils-ping
ll git
#RUN apt-get install -y rbenv ruby-build
#RUN git clone https://github.com/rbenv/rbenv.git ~/.rbenv
#RUN export PATH="$HOME/.rbenv/bin:$PATH"
#RUN eval "$(rbenv init -)"
#RUN exec $SHELL

#RUN git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build
#FROM ruby:2.7.2
#RUN rbenv install --list
#RUN rbenv install 2.7.2
#RUN rbenv global 2.7.2
#RUN apt-get update
#run apt-get -y install sudo

#RUN useradd -m docker && echo "docker:docker" | chpasswd && adduser docker sudo
#USER docker
run apt-get -y install gcc
run apt-get -y install make 
run apt-get -y install wget
run apt-get -y install libssl-dev libreadline-dev
run mkdir /tmp/ruby272
workdir /tmp/ruby272 
run wget https://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.2.tar.gz
run tar xzvf ruby-2.7.2.tar.gz
workdir /tmp/ruby272/ruby-2.7.2
run ./configure
run make
run make install




#CMD /bin/bash




#run apt-get -y install wget
#run wget https://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.2.tar.gz
#run sudo dpkg -i ruby-2.7.2.tar.gz  


entrypoint ping 8.8.8.8 

