Vagrant.configure("2") do |config|
  config.vm.box = "TimeS-Dev/centos7wpse"
  config.vm.box_version = "0.0.1"
  config.ssh.private_key_path = "~/.ssh/id_rsa"
  config.ssh.forward_agent = true
#  config.ssh.username = 'vagrant'
#  config.ssh.password = 'vagrant'
#  config.ssh.insert_key = false
  config.vm.network "forwarded_port", guest: 80, host: 8080

end
