Vagrant.configure("2") do |config|
#config.vm.box = "ubuntu/focal64"
    
    config.vm.define "wordpress" do |web_server|
        web_server.vm.box = "ubuntu/focal64"
        web_server.vm.provision "shell", path: "wordpress.sh"
        web_server.vm.network "forwarded_port", guest: 80, host: 8080
        #web_server.vm.hostname = "web"
        #web_server.vm.network ip: "192.168.56.2"
    end
    
    config.vm.define "mysql" do |database|
        database.vm.box = "ubuntu/focal64"
        database.vm.provision "shell", path: "database.sh"
        
        #database.vm.network "private_network", ip: "192.168.56.3"
    end
end