version: "3.8"

services:

  wordpress:
    build:
      context: ./wordpress
    container_name: wordpress-webserver
    restart: always
    depends_on:
      - cache
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
      
  phpmyadmin:    
    image: phpmyadmin:latest
    container_name: phpmyadmin-server
    restart: always
    environment:
      - PMA_HOST=xyz
      - PMA_PORT=3306
    
  cache:
    image: redis:latest
    container_name: redis-cache
    restart: always
    command: redis-server --save 20 1 --loglevel warning

  nginx:
    build:
      context: ./nginx-reverse-proxy
    container_name: nginx_reverse_proxy
    restart: always
    ports:
      - "80:80"
    

    
